### ISSUE TITLE
NoSuchMethodError on startup

### ISSUE THREAD

**Issue by LooFifteen** [Project-Cepi/LuckPerms#1]
### Description

On startup, LuckPerms produces an error to do with getting the version of Minestom server.

### Reproduction steps

1. Start the server.

### Expected behaviour

To start without an error.

### Environment details

* Server type/version: `Sabre` running version `0.14`
* LuckPerms version: `Minestom`

```
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.minestom.server.Bootstrap.bootstrap(Bootstrap.java:46)
        at world.cepi.sabre.BootstrapWrapper.main(BootstrapWrapper.java:10)
Caused by: java.lang.NoSuchMethodError: 'net.minestom.server.extensions.DiscoveredExtension me.lucko.luckperms.minestom.LPMinestomBootstrap.getOrigin()'
        at LuckPerms//me.lucko.luckperms.minestom.LPMinestomBootstrap.getVersion(LPMinestomBootstrap.java:120)
        at LuckPerms//me.lucko.luckperms.common.locale.Message.lambda$static$0(Message.java:120)
        at LuckPerms//me.lucko.luckperms.common.locale.Message$Args1.send(Message.java:4066)
        at LuckPerms//me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:118)
        at LuckPerms//me.lucko.luckperms.minestom.LPMinestomBootstrap.initialize(LPMinestomBootstrap.java:89)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
        at Minestom Root ClassLoader//net.minestom.server.MinecraftServer.start(MinecraftServer.java:785)
        at Minestom Root ClassLoader//net.minestom.server.MinecraftServer.start(MinecraftServer.java:807)
        at Minestom Root ClassLoader//world.cepi.sabre.SabreKt.main(Sabre.kt:17)
        at Minestom Root ClassLoader//world.cepi.sabre.SabreKt.main(Sabre.kt)
        ... 6 more
```

### Any other relevant details

May need updating, I'm not sure.

**Comment by kezz** [comment]
Very odd - I'll check if that method has been removed and drop another update.

**Comment by LooFifteen** [comment]
I'm still getting this error with the latest update on Sabre 0.14, I'm starting to believe this is a classloader issue.
